### ISSUE TITLE
libs/libpcre.so: error adding symbols: File in wrong format (while Cross Compiling)

### ISSUE THREAD

**Issue by ghost** [vmg/libpcre#2]
I'm trying to compile pcre-v8.43 using arm-linux-gnueabihf-gcc cross compiler tool:

my config command is:

./configure --host=arm-linux CC=arm-linux-gnueabihf-gcc --prefix=/home/pcre-8.43/_install --enable-pcre32

it runs well but when i make is i got this error:
./.libs/libpcre.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:1577: recipe for target 'libpcrecpp.la' failed
make[1]: *** [libpcrecpp.la] Error 1
make[1]: Leaving directory '/home/pcre-8.43'
Makefile:1403: recipe for target 'all' failed
make: *** [all] Error 2

is there any solution to this issue?

**Comment by recvfrom** [comment]
This is currently the top result from Google if you search for `./.libs/libpcre.so: error adding symbols: File in wrong format`, so to add a solution, you need to specify the path to the C++ compiler via `CXX` or else `configure` will choose the system `g++`.  Here's an example invocation building for MIPS that works (using the toolchain installed on Ubuntu via `sudo apt-get install gcc-multilib-mips-linux-gnu gcc-mips-linux-gnu g++-mips-linux-gnu`):

```
CC=mips-linux-gnu-gcc CXX=mips-linux-gnu-g++ ./configure --build=i686-pc-linux-gnu --host=mips-linux-gnu --prefix `pwd`/installed_mips
```
